name: Android tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # this job runs all the tests
  test_on_android:
    # there's no need to run it on forks
    if: github.repository == 'spacecowboy/NotePad'
    runs-on: macos-latest # it has hardware acceleration
    timeout-minutes: 15
    strategy:
      matrix:
        # test the app on emulators with these OS versions installed
        api-level: [ 23, 29, 30, 31, 32 ] # TODO keep only 23 and 32 if they both work
    permissions:
      contents: read
    steps:
      - name: perform the checkout
        uses: actions/checkout@v3

      - name: perform the set up for the JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: 'gradle'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          script: echo "Generated AVD snapshot for caching."

      - name: run the tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -no-boot-anim -camera-back none
          script: ./gradlew connectedCheck --stacktrace

      - name: Upload test report when tests fail
        # because the printed out stacktrace (console) is too short
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: android-test-report-api${{ matrix.api-level }}
          path: app/build/reports/androidTests/connected/**
