name: Android tests

on:
  push: # runs when you commit to the master branch, so also when merging pull requests
    branches: [ "master" ]
# running on every pull request uses too much server time => avoid it

jobs:
  # this job runs all the tests
  test_on_android:
    if: github.repository == 'spacecowboy/NotePad' # no need to run it on forks
    # it has hardware acceleration. Full list of installed software:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-12
    timeout-minutes: 45
    strategy:
      matrix:
        # test on emulators with these OS versions
        api-level: [ 23, 28, 32 ] # minSdk, average, targetSdk
    permissions:
      contents: read
    steps:
      - name: perform the checkout
        uses: actions/checkout@v3

      - name: perform the validation
        uses: gradle/wrapper-validation-action@v1

      - name: perform the set up for the JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: 'gradle'

      - name: perform Gradle caching
        uses: gradle/gradle-build-action@v2

      - name: perform HAXM installation
        # it still does not work: check the log for the next step
        run: brew install intel-haxm

      - name: Check for HAXM installation
        # ignoring the return code. Read the console log to know the result
        run: emulator -accel-check || true

      - name: perform AVD caching
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        # here it automatically installs the needed android SDK components
        # see https://github.com/ReactiveCircus/android-emulator-runner/blob/main/README.md 
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis # the images for API 32 only have this target
          arch: x86_64        # the only one available for all API versions
          profile: Nexus 5X   # I test on this in my PC
          disk-size: 1G       # for saving org and json files
          force-avd-creation: false
          # you need -no-window to make it work
          emulator-options: -gpu swiftshader_indirect -noaudio -no-boot-anim -no-window
          disable-animations: true
          # start the emulator, run this script, then close the emulator
          script: |
            screencapture screenshot1.jpg
            echo " - - - OK - - - "

      - name: perform the Gradle build
        run: ./gradlew build

      - name: take a screenshot of the VM before the tests
        run: screencapture screenshot2.jpg

      - name: run the tests
        # note that by now the app is already built
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: Nexus 5X
          disk-size: 1G
          force-avd-creation: false
          disable-animations: true
          emulator-options: -no-snapshot-save -verbose -noaudio -no-boot-anim
          script: |          
            # take screenshot after the emulator starts            
            screencapture screenshot3.jpg
            # close all OS popups in the emulator
            adb shell am broadcast -a android.intent.action.CLOSE_SYSTEM_DIALOGS
            # wait 30'' for emulator
            sleep 30
            # run tests
            ./gradlew connectedCheck --debug --stacktrace

      - name: take a screenshot at the end # 99% useless
        if: success() || failure()
        run: screencapture screenshot4.jpg

# upload results

      - name: upload the screenshots
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: screenshots_of_tests_api${{ matrix.api-level }}
          path: |
            screenshot1.jpg
            screenshot2.jpg
            screenshot3.jpg
            screenshot4.jpg

      - name: Upload detailed test reports
        # because the printed out stacktrace (console) is too short
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: android-test-report-api${{ matrix.api-level }}
          path: app/build/reports/androidTests/connected/**
