name: Android tests

on:
  push:
    branches: [ "master" ]
# running on every pull request uses too much server time
#  pull_request:
#    branches: [ "master" ]

jobs:
  # this job runs all the tests
  test_on_android:
    # there's no need to run it on forks
    if: github.repository == 'spacecowboy/NotePad'
    runs-on: macos-latest # it has hardware acceleration
    timeout-minutes: 35
    strategy:
      matrix:
        # test the app on emulators with these OS versions installed
        api-level: [ 23, 32 ]
    permissions:
      contents: read
    steps:
      - name: perform the checkout
        uses: actions/checkout@v3

      - name: perform the validation
        uses: gradle/wrapper-validation-action@v1

      - name: perform the set up for the JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: 'gradle'

      - name: perform Gradle caching
        uses: gradle/gradle-build-action@v2

# it shows a popup when it finishes installation: this prevents the tests from starting!
#      - name: perform HAXM installation
#        run: brew install --cask intel-haxm

#      - name: perform ffmpeg installation
#        run: brew install ffmpeg

      - name: perform AVD caching
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis # the images for API 32 only have this target
          arch: x86_64        # the only one available for images of all API versions
          profile: Nexus 5X
          force-avd-creation: false
          disable-animations: true
          script: echo " - - - Generated AVD snapshot for caching - - - "

#      - name: record a video of the session
#        run: |
#          ffmpeg -f avfoundation -i 0 -t 120 video.mov &

      - name: perform the Gradle build
        run: ./gradlew build

      - name: run the tests
        # note that by now the app is already built
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: Nexus 5X
          force-avd-creation: false
          disable-animations: true
          emulator-options: -no-snapshot-save -no-window -no-boot-anim -camera-back none
          script: |
            # take a screenshot of the VM to verify that the emulator started
            screencapture screenshot1.jpg            
            # test
            ./gradlew connectedCheck --stacktrace
            # take a screenshot at the end
            screencapture screenshot2.jpg

#      - name: upload the video
#        uses: actions/upload-artifact@v3
#        with:
#          name: video.mov
#          path: video.mov

      - name: upload the screenshot n°1
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshot1.jpg
          path: screenshot1.jpg

      - name: upload the screenshot n°2
        uses: actions/upload-artifact@v3
        with:
          name: screenshot2.jpg
          path: screenshot2.jpg

      - name: Upload test report when tests fail
        # because the printed out stacktrace (console) is too short
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: android-test-report-api${{ matrix.api-level }}
          path: app/build/reports/androidTests/connected/**
