name: Android tests

on:
  push: # runs when you commit to the master branch, so also when merging pull requests
    branches: [ "master" ]
# running on every pull request uses too much server time => avoid it

jobs:
  # this job runs all the tests
  test_on_android:
    if: github.repository == 'spacecowboy/NotePad' # no need to run it on forks
    # it has hardware acceleration. Full list of installed software:
    # https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
    runs-on: macos-12    
    timeout-minutes: 45
    strategy:
      matrix:
        # test on emulators with these OS versions
        api-level: [ 28, 32 ] # minSdk, average, targetSdk
    permissions:
      contents: read
    steps:
      - name: perform the checkout
        uses: actions/checkout@v3

      - name: perform the validation
        uses: gradle/wrapper-validation-action@v1

      - name: perform the set up for the JDK
        uses: actions/setup-java@v3        
        with:
          java-version: 11
          distribution: temurin
          # this step should not cache gradle

      - name: perform Gradle setup & caching
        uses: gradle/gradle-build-action@v2        

      - name: Check for HAXM installation
        # ignoring the return code. Read the console log to know the result
        run: emulator -accel-check || true
        # it's not installed. You would install it with "brew install intel-haxm", but it doesn't work

      - name: perform AVD caching
        uses: actions/cache@v3
        id: avd-cache        
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        # here it automatically installs the needed android SDK components
        # see https://github.com/ReactiveCircus/android-emulator-runner/blob/main/README.md 
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis # the images for API 32 only have this target
          arch: x86_64        # the only one available for all API versions
          profile: Nexus 5X   # I test on this in my PC
          disk-size: 1G       # for saving org and json files
          force-avd-creation: false
          # you need these parameters to make it work
          emulator-options: -gpu swiftshader_indirect -no-boot-anim -no-window
          disable-animations: true
          # start the emulator, run this script, then close the emulator
          script: |
            # the emulator is still active
            adb emu screenrecord screenshot ./screenshot-emu1.png
            echo " - - - OK - - - "

      - name: perform the Gradle build
        run: ./gradlew build      

#      - name: install ffmpeg
#        run: brew install ffmpeg

      - name: run the tests
        # note that by now the app is already built
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: Nexus 5X
          disk-size: 1G          
          force-avd-creation: false
          disable-animations: true
          emulator-options: -no-snapshot-save -verbose -no-boot-anim -gpu swiftshader_indirect -no-window
          script: |          
            # take screenshot of the host PC after the emulator starts. MacOS specific
            screencapture screenshot-desktop.jpg            
            # output may be useful
            adb devices
            # close all OS popups in the emulator, like "System UI stopped working"
            adb shell am broadcast -a android.intent.action.CLOSE_SYSTEM_DIALOGS   
            # close that useless popup that tells you how to exit fullscreen mode
            adb shell settings put secure immersive_mode_confirmations confirmed            
            # uninstall the app (it can't uninstall it by itself), ignore any error
            adb shell pm uninstall --user 0 com.nononsenseapps.notepad.test || true
            adb shell pm uninstall --user 0 com.nononsenseapps.notepad || true
            # Take a screenshot of the emulator. See also
            # https://developer.android.com/studio/run/advanced-emulator-usage#screenshots
            adb emu screenrecord screenshot ./screenshot-emu2.png
            # record the tests in the emulator (dies after 3 minutes!)
            # adb emu screenrecord start --bit-rate 100000 --size 540x960 ./emu-video.webm
            # make a function to record 3 minutes and save the video to the host PC
            record_and_move() { adb shell screenrecord --output-format=h264 --bit-rate 100000 --size 540x960 /sdcard/video$1.mp4 ; adb pull /sdcard/video$1.mp4 . ; }
            # call the function 5 times, in series, in background
            { record_and_move V1 ; record_and_move V2 ; record_and_move V3 ; record_and_move V4 ;  record_and_move V5 ;  } &
            # meanwhile, run tests
            ./gradlew connectedCheck
            # stop recording. Useless: if the script succeeds, videos are useless. 
            # If it fails, the entire script is killed
            # adb emu screenrecord stop
      
# upload results

      - name: upload the video and screenshots
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: screenshots_of_tests_api${{ matrix.api-level }}
          path: |
            screenshot-desktop.jpg                        
            screenshot-emu1.png
            screenshot-emu2.png
            emu-video.webm

      - name: Upload detailed test reports
        # because the printed out stacktrace (console) is too short
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: android-test-report-api${{ matrix.api-level }}
          path: app/build/reports/androidTests/connected/**
