name: Android tests

on:
  push: # runs when you commit to the master branch, so also when merging pull requests
    branches: [ "master" ]
# running on every pull request uses too much server time
#  pull_request:
#    branches: [ "master" ]

jobs:
  # this job runs all the tests
  test_on_android:
    if: github.repository == 'spacecowboy/NotePad' # no need to run it on forks
    runs-on: macos-latest # it has hardware acceleration
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [ 23, 28, 32 ] # test on emulators with these OS versions
    permissions:
      contents: read
    steps:
      - name: perform the checkout
        uses: actions/checkout@v3

      - name: perform the validation
        uses: gradle/wrapper-validation-action@v1

      - name: perform the set up for the JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "temurin"
          cache: 'gradle'

      - name: perform Gradle caching
        uses: gradle/gradle-build-action@v2

      - name: Check for HAXM installation
        # ignoring the return code: read the console log to know the result
        run: emulator -accel-check || true

# if the step above detects no HAXM, we may want to install it (?)
#      - name: perform HAXM installation
#        run: brew install --cask intel-haxm

      - name: perform AVD caching
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        # here it automatically installs the needed android SDK components
        # see https://github.com/ReactiveCircus/android-emulator-runner/blob/main/README.md 
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis # the images for API 32 only have this target
          arch: x86_64        # the only one available for all API versions
          profile: Nexus 5X
          force-avd-creation: false
          # you need -no-window to make it work
          emulator-options: -gpu swiftshader_indirect -noaudio -no-boot-anim -no-window
          disable-animations: true
          script: echo " - - - OK - - - "

      - name: perform the Gradle build
        run: ./gradlew build

      - name: take a screenshot of the VM before the tests
        run: screencapture screenshot1.jpg

      - name: run the tests
        # note that by now the app is already built
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: Nexus 5X
          force-avd-creation: false
          disable-animations: true
          emulator-options: -no-snapshot-save -gpu swiftshader_indirect -noaudio -no-boot-anim -no-window
          script: |          
            # take screenshot after the emulator starts            
            screencapture screenshot2.jpg
            # run tests
            ./gradlew connectedCheck # --stacktrace

      - name: take a screenshot at the end # 99% useless
        run: screencapture screenshot3.jpg

# upload results

      - name: upload the screenshots
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: screenshots_of_tests
          path: |
            screenshot1.jpg
            screenshot2.jpg
            screenshot3.jpg

      - name: Upload detailed test reports
        # because the printed out stacktrace (console) is too short
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: android-test-report-api${{ matrix.api-level }}
          path: app/build/reports/androidTests/connected/**
